//FIXME:отсутствие авторских прав
//
//FIXTO:
// @copyright MineMoon. All rights reserved.

package ru.mastiko.mfiller;

import java.util.List;
import java.util.function.IntFunction;

// FIXME: Отсутствует Javadoc для класса и методов,
// отступы составляют 4 пробела вместо 2,
// в названии метода допущена опечатка (Hungred -> Hundred),
// магические числа (100) должны быть вынесены в константы,
// имя параметра Converter начинается с большой буквы (нарушение camelCase),
// отсутствуют пробелы внутри скобок в некоторых местах,
// утилитарный класс должен иметь приватный конструктор и быть final,
// отсутствует проверка на null для параметра list.
// public class Mfiller {
//     public static <T extends Number> void oneHungredFiller(
//             List<T> list,
//             IntFunction<T> Converter ) {

//         if (Converter == null ) {
//             throw new NullPointerException("Converters cannot be null");
//         }

//         for (int i = 1; i <= 100; i++) {
//             list.add(Converter.apply(i));
//         }
//     }
// }
//
// FIXTO:

/**
 * Utility class for filling lists with generated numerical data.
 */
public final class Mfiller {

  private static final int FILL_LIMIT = 100;

  /**
   * Private constructor to prevent instantiation.
   */
  private Mfiller() {
    throw new UnsupportedOperationException("Utility class");
  }

  /**
   * Fills the provided list with 100 elements generated by the given function.
   *
   * @param <T>       the type of numbers in the list.
   * @param list      the list to be filled.
   * @param generator the function that generates a value based on an index.
   * @throws IllegalArgumentException if list or generator is null.
   */
  public static <T extends Number> void oneHundredFiller(
      List<T> list,
      IntFunction<T> generator) {

    if (list == null) {
      throw new IllegalArgumentException("Target list cannot be null.");
    }

    if (generator == null) {
      throw new IllegalArgumentException("Generator function cannot be null.");
    }

    for (int i = 1; i <= FILL_LIMIT; i++) {
      list.add(generator.apply(i));
    }
  }
}
