//FIXME:отсутствие авторских прав (2 стр.),
//
//FIXTO:
// @copyright MineMoon. All rights reserved.
package ru.mastiko.pairfiller;

import java.util.List;
import java.util.function.IntFunction;
import ru.mastiko.Mpair.Pair;

// FIXME: Отсутствует Javadoc для класса и методов,
// отступы составляют 4 пробела вместо 2,
// в названии метода допущена опечатка (Hungred -> Hundred),
// используется магическое число (100),
// утилитарный класс должен иметь приватный конструктор и быть final,
// отсутствует проверка на null для параметра list,
// используется NullPointerException вместо IllegalArgumentException.
// public class Pairfiller {

//     public static <T extends Number, U extends Number> void oneHungredFiller(
//             List<Pair<T, U>> list,
//             IntFunction<T> firstConverter,
//             IntFunction<U> secondConverter) {

//         if (firstConverter == null || secondConverter == null) {
//             throw new NullPointerException("Converters cannot be null");
//         }

//         for (int i = 1; i <= 100; i++) {
//             list.add(new Pair<>(firstConverter.apply(i), secondConverter.apply(i)));
//         }
//     }
// }
//
// FIXTO:
/**
 * Utility class for filling lists with Pair objects containing numerical data.
 */
public final class Pairfiller {

  private static final int FILL_LIMIT = 100;

  /**
   * Private constructor to prevent instantiation of this utility class.
   */
  private Pairfiller() {
    throw new UnsupportedOperationException("Utility class cannot be instantiated");
  }

  /**
   * Fills the provided list with 100 Pair objects generated by the given functions.
   *
   * @param <T>             the type of the first element in the pair.
   * @param <U>             the type of the second element in the pair.
   * @param list            the list to be filled with pairs.
   * @param firstGenerator  function to generate the first element of each pair.
   * @param secondGenerator function to generate the second element of each pair.
   * @throws IllegalArgumentException if list or any generator is null.
   */
  public static <T extends Number, U extends Number> void oneHundredFiller(
      List<Pair<T, U>> list,
      IntFunction<T> firstGenerator,
      IntFunction<U> secondGenerator) {

    if (list == null) {
      throw new IllegalArgumentException("Target list cannot be null.");
    }
    if (firstGenerator == null || secondGenerator == null) {
      throw new IllegalArgumentException("Generator functions cannot be null.");
    }

    for (int i = 1; i <= FILL_LIMIT; i++) {
      list.add(new Pair<>(firstGenerator.apply(i), secondGenerator.apply(i)));
    }
  }
}